version: '3'

services:
  exness_db:
    image: postgres:12
    ports:
      - 54321:5432
#    volumes:
#      - ./init/postgres:/var/lib/postgres
#      - ./../init/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres